/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package dao;

import entities.Question;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/**
 *
 * @author Valentina Sarais
 */
public class QuestionDao {

    Connection connection;

    public QuestionDao() {
        connection = MariadbConnection.getInstance();
    }

    public Question readRandomQuestion() {
        Question randomQuestion = null;
        String sql = "SELECT * FROM question";
        PreparedStatement pstmt;

        try {
            pstmt = connection.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();

            List<Question> questionList = new ArrayList<>();

            // Récupérer toutes les questions de la base de données
            while (rs.next()) {
                Question question = new Question();
                question.setId_question(rs.getInt("id_question"));
                question.setEnonce(rs.getString("enonce"));
                question.setReponse(rs.getString("reponse"));
                questionList.add(question);
            }

            // Choisir une question aléatoire
            if (!questionList.isEmpty()) {
                Random random = new Random();
                int index = random.nextInt(questionList.size());
                randomQuestion = questionList.get(index);
            }

        } catch (SQLException ex) {
            System.out.println("Erreur lors de la lecture d'une question aléatoire : " + ex.getMessage());
        }

        return randomQuestion;
    }

    public Question getQuestionByEnonce(String enonce) {
        Question question = null;
        String sql = "SELECT * FROM question WHERE enonce = ?";
        try {
            PreparedStatement pstmt = connection.prepareStatement(sql);
            pstmt.setString(1, enonce);
            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) {
                question = new Question();
                question.setId_question(rs.getInt("id_question"));
                question.setEnonce(rs.getString("enonce"));
                question.setReponse(rs.getString("reponse"));
            }
        } catch (SQLException ex) {
            System.out.println("Erreur lors de la récupération de la question par énoncé : " + ex.getMessage());
        }
        return question;
    }

    public boolean verifierReponseUtilisateur(int idQuestion, String reponseUtilisateur) {
        boolean reponseCorrecte = false;
        String sql = "SELECT reponse FROM question WHERE id_question = ?";
        try {
            PreparedStatement pstmt = connection.prepareStatement(sql);
            pstmt.setInt(1, idQuestion);
            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) {
                String reponseCorrecteDB = rs.getString("reponse");
                // Supprimer les espaces en début et fin de chaîne
                reponseCorrecteDB = reponseCorrecteDB.trim();
                reponseUtilisateur = reponseUtilisateur.trim();
                // Vérifier si la réponse de l'utilisateur correspond à la réponse correcte 
                //(insensible à la casse)
                reponseCorrecte = reponseCorrecteDB.equalsIgnoreCase(reponseUtilisateur);
            }
        } catch (SQLException ex) {
            System.out.println("Erreur lors de la vérification de la réponse de l'utilisateur : " + ex.getMessage());
        }
        return reponseCorrecte;
    }

    /************** CRUD pour l'admin
     * @param objQ *************/
    
    //l'admin peut ajouter des nouvelles questions-reponse sur la BDD 
    public void create(Question objQ) {
        String sql = "INSERT INTO question (id_question, enonce, reponse) VALUES (?, ?, ?)";
        try (PreparedStatement pstmt = connection.prepareStatement(sql, PreparedStatement.RETURN_GENERATED_KEYS)) {
            pstmt.setInt(1, objQ.getId_question());
            pstmt.setString(2, objQ.getEnonce());
            pstmt.setString(3, objQ.getReponse());
            int nbLines = pstmt.executeUpdate();
            if (nbLines == 1) {
                ResultSet autoGeneratedKeys = pstmt.getGeneratedKeys();
                autoGeneratedKeys.first();
                int id = autoGeneratedKeys.getInt(1);
                objQ.setId_question(id);
            }
        } catch (SQLException ex) {
            System.err.println("Erreur lors de l'insertion : " + ex.getMessage());
        }
    }


      public Question read(Integer id) {
        Question objQ = null;
        String sql = "SELECT * FROM question WHERE id_question=?";
        try (PreparedStatement pstmt = connection.prepareStatement(sql)) {
            pstmt.setInt(1, id);
            ResultSet rs = pstmt.executeQuery();
            if (rs.first()) {
                objQ = new Question();
                objQ.setId_question(rs.getInt("id_question"));
                objQ.setEnonce(rs.getString("enonce"));
                objQ.setReponse(rs.getString("reponse"));
 
            }
        } catch (SQLException ex) {
            System.err.println("Erreur lors de la lecture : " + ex.getMessage());
        }
        return objQ;
    }


     public void update(Question objQ) {
        String sql = "UPDATE question SET id_question=?, enonce=?, reponse=? WHERE id_question=?";
        try (PreparedStatement pstmt = connection.prepareStatement(sql)) {
            pstmt.setInt(1, objQ.getId_question());
            pstmt.setString(2, objQ.getEnonce());
            pstmt.setString(3, objQ.getReponse());
            pstmt.executeUpdate();
        } catch (SQLException ex) {
            System.err.println("Erreur lors de l'update : " + ex.getMessage());
        }
    }

    public void delete(Integer id) {
        String sql = "DELETE FROM question WHERE id_question=?";
        try (PreparedStatement pstmt = connection.prepareStatement(sql);) {
            pstmt.setInt(1, id);
            pstmt.executeUpdate();
        } catch (SQLException ex) {
            System.err.println("Erreur lors du delete : " + ex.getMessage());
        }
    }

}
